name: vendorize
version: 0.1
summary: Vendorize a given snap
description: |
  A given snap will be prepared to vendorize all dependencies pulled
  in from sources outside the allowed hosts effectively creating stable
  branches to make rebuilds safe.

grade: devel
confinement: strict

apps:
  vendorize:
    command: bin/vendorize
    plugs: [home, network, ssh-keys]
    environment:
      PATH: $PATH:$SNAP/usr/lib/git-core
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      # Under confinement multiplexing SSH sessions won't work
      GIT_SSH_COMMAND: ssh -o ControlMaster=no

parts:
  vendorize:
    plugin: python
    requirements: requirements.txt

  tools:
    plugin: nil
    stage-packages:
     - git
     - gettext-base

  bin:
    plugin: dump
    stage:
      - bin/vendorize
